version: '1'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8900"
    container_name: bidstake
    volumes:
      - .:/bidstake
    ports: 
      - "8900:8900"